### ISSUE TITLE
Jekyll doesn't live reload

### ISSUE THREAD

**Issue by NealHumphrey** [codefordc/project-management#30]
While running the `docker-compose up` from the root of housing-insights dev branch: github.com/codefordc/housing-insights

Have to restart docker compose for changes to Jekyll site to be displayed. 

I used the instructions to build a custom Jekyll image (using edits to instructions noted in issue #23)
 
This is the relevant part of the docker compose file:
```
  jekyll:
        image: codefordc2/housing-insights-jekyll
        command:
            - jekyll serve --watch --incremental
        volumes:
            - ./docs:/srv/jekyll
        ports:
            - "4000:4000"
```

When I run this command directly, instead of docker-compose, I also do not get live reloading:
`docker run --volume $(pwd)/docs:/srv/jekyll -p 192.168.99.100:4000:4000 codefordc2/housing-insights-jekyll`

I'm guessing the problem is probably in the docker image? Is there something in the [Jekyll Dockerfile](https://github.com/codefordc/project-management/blob/master/jekyll/Dockerfile) that needs to be changed to allow the image to use live reloading?
